# Magnum CI: Hosted Continuous Integration Platform
# https://magnum-ci.com

#before_install:

install:
  # requires PHP5.5 instead of the current version
  - sudo apt-get install --yes --quiet python-software-properties
  - sudo add-apt-repository --yes ppa:ondrej/php5
  # requires PHP with Internationalization extension
  - sudo apt-get update --yes --quiet
  - sudo apt-get install --yes --quiet php5 php5-intl

before_script:
  # explicit Composer configuration for Magnum CI
  - export COMPOSER_CACHE_DIR=.composer-cache/

script:
  - sh phing.sh phpunit.run

#after_script:
