# Magnum CI: Hosted Continuous Integration Platform
# https://magnum-ci.com

#before_install:

install:
  # requires PHP with Internationalization extension 
  - sudo apt-get update --yes --quiet
  - sudo apt-get install --yes --quiet php5 php5-intl

before_script:
  # explicit Composer configuration for Magnum CI
  - export COMPOSER_CACHE_DIR=.composer-cache/
  - composer config github-oauth.github.com $githubToken

script:
  - sh phing.sh phpunit.run

#after_script:
