# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0

branches:
    only:
        - master
        - develop
        - release/2.3_LTS
        - release/2.7_LTS

env:
    global:
        - COMPOSER_CACHE_DIR=.composer-cache/

script: ./phing.sh phpunit.run
