# Set parameters of the app
parameters:
    database_driver:   pdo_mysql
    database_host:     ~
    database_port:     ~
    database_name:     ~
    database_user:     ~
    database_password: ~

    mailer_transport: mail
    mailer_host:      ~
    mailer_user:      ~
    mailer_password:  ~
