homepage:
    pattern: /
    defaults: { _controller: "KmeliaFreshBundle:Homepage:homepage" }
    requirements: { _method: GET }

no_http_cache_homepage:
    pattern: /no-http-cache
    defaults: { _controller: "KmeliaFreshBundle:Homepage:noHttpCacheHomepage" }
    requirements: { _method: GET }
