homepage:
    path: /
    defaults: { _controller: "KmeliaFreshBundle:Homepage:homepage" }
    methods:  [GET]

http_cache_from_routing_homepage:
    path: /http-cache-from-routing
    defaults:
        _controller: "KmeliaFreshBundle:Homepage:httpCacheFromRoutingHomepage"
        http_cache_duration: 1
    methods:  [GET]

http_cache_from_controller_homepage:
    path: /http-cache-from-controller
    defaults: { _controller: "KmeliaFreshBundle:Homepage:httpCacheFromControllerHomepage" }
    methods:  [GET]

no_http_cache_homepage:
    path: /no-http-cache
    defaults: { _controller: "KmeliaFreshBundle:Homepage:noHttpCacheHomepage" }
    methods:  [GET]

secured_area:
    path: /secured-area
    defaults: { _controller: "KmeliaFreshBundle:Homepage:homepage" }
    methods:  [GET]
