homepage:
    path: /
    defaults: { _controller: "KmeliaFreshBundle:Homepage:homepage" }
    methods:  [GET]

no_http_cache_homepage:
    path: /no-http-cache
    defaults: { _controller: "KmeliaFreshBundle:Homepage:noHttpCacheHomepage" }
    methods:  [GET]

secured_area:
    path: /secured-area
    defaults: { _controller: "KmeliaFreshBundle:Homepage:homepage" }
    methods:  [GET]
