# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~
    
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
        main:
            pattern: ^/
            anonymous: ~
            http_basic:
                realm: "Secured with HTTP basic"
                provider: in_memory
    
    access_control:
        - { path: ^/secured-area, role: ROLE_USER }
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }
