parameters:
    locale: en
    secret: SeriouslyYouHaveToChangeIt!

framework:
    secret: "%secret%"
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: true
